#!/bin/bash

PACKAGE="qemu-utils"
COMMAND=""
INPUT_FILE=""
OUTPUT_FILE=""
INPUT_TYPE=""
OUTPUT_TYPE=""

query_package()
{
   echo "Checking installed packages..."

   local pkg=$(dpkg-query -l $PACKAGE | grep -o $PACKAGE)

   if [ ! $pkg ] ; then
       install_package
   fi

   echo "qemu-utils is installed....skipping"
}

install_package()
{
   echo "Installing package $PACKAGE..."

   sudo apt-get install $PACKAGE
}

convert()
{
   echo "Converting image..."

   sudo qemu-img $COMMAND -f $INPUT_TYPE $INPUT_FILE -O $OUTPUT_TYPE $OUTPUT_FILE

   echo "Conversion process complete"
}

parse_args()
{
   if [ $# -eq 0 ] ; then
      help
     exit 0
   fi

   while getopts "c:f:o:i:t:h" option ;
   do
      case "${option}" in
         c)
            COMMAND=${OPTARG}
            ;;
         f)
            INPUT_FILE=${OPTARG}
            ;;
         o)
            OUTPUT_FILE=${OPTARG}
            ;;
         i)
            INPUT_TYPE=${OPTARG}
            ;;
         t)
            OUTPUT_TYPE=${OPTARG}
            ;;
         h)
            help
            exit 0
            ;;
      esac
   done
}

help()
{
   echo "Usage: img-convert -c [command] {-f -o -i -t}"
   echo " -c               command (convert)"
   echo " -f               input file"
   echo " -o               output file"
   echo " -i               input file type (qcow2, raw, vdi, vmdk)"
   echo " -t               output file type (qcow2,raw, vdi, vmdk)"
   echo " -h               print help"
}

main()
{
   parse_args $@
   query_package
   convert
}

main $@
